name: Deploy Games
on:
  workflow_dispatch:

  push:
    paths:
      - 'games/**'
      - '.github/workflows/deploy-games.yml'
      - 'bin/deploy-games.ts'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: "0.16.0-dev.1303+ee0a0f119"
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy games
        run: bun run deploy-games
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
